apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtc-operator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.openshift-gitops.argoproj.io
spec:
  destination:
    namespace: mtc-operator
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: mtc-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}